version: '2'
services:
  app:
    # Ensure the database is running before running server
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./dockerConfig/Dockerfile
    container_name: AppJS
    #command: npm runServer
    links:
     - db
    ports:
     - "3232:3232" # JS
     - "5858:5858" # Node Debug
    environment:
     - NODE_ENV=development # production for staging
    volumes:
     - ./:/home/app/filesharing
     - /home/app/filesharing/node_modules/

  db:
    build:
      context: .
      dockerfile: ./dockerConfig/Dockerfile-mongo
    container_name: AppDB
    ports:
     - "27017:27017"

  # This adds the premade database to 'db' container
  mongo-seed:
    build:
      context: .
      dockerfile: ./dockerConfig/Dockerfile-mongo-seed
    links:
      - db
