version: '2'
services:
  app:
    # Ensure the database is running before running server
    depends_on:
      - db
    build: .
    container_name: AppJS
    #command: npm runServer
    links:
     - db
    ports:
     - "3232:3232" # JS
     - "5858:5858" # Node Debug
     - "35729:35729" # Livereload
     - "8080:8080" # change to whatever port is to be used
    environment:
     - NODE_ENV=development # production for staging
    volumes:
     - ./:/home/app/filesharing
     - /home/app/filesharing/node_modules/

  db:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: AppDB
    ports:
     - "27017:27017"
