# Thanks to http://stackoverflow.com/questions/31210973/how-do-i-seed-a-mongo-database-using-docker-compose

FROM mongo

# Copy the database dump files so that we can import it to the database
COPY ./dump /dump

# This restores the database into the "db" container(defined in docker-compose)
CMD mongorestore --host db --dir /dump
